// Generates the Zendo suite mark: a brushed ensō holding four stones in the application colours.
// Writes favicon.svg (repository root), src/renderer/public/favicon.svg, and the path data the
// in-app icon uses (src/renderer/src/ui/suite-mark.ts). Run: pnpm icon:generate
// The Dock/packaged icon (build/icon.png) is a 1024 px render of favicon.svg; re-export it after changes.
import { writeFileSync } from 'node:fs'

const viewBox = 32
const centre = 16
const plate = '#23262d'
const ink = '#f4f1ea'

/** Application colours, one set for the logo, the app icons and each window's accent. */
const stones = [
  { app: 'Ledger', colour: '#2fb592', x: 16, y: 12.8 },
  { app: 'Hanko', colour: '#f06a52', x: 19.2, y: 16 },
  { app: 'Sumi', colour: '#7d97df', x: 16, y: 19.2 },
  { app: 'Slides', colour: '#e0a92c', x: 12.8, y: 16 },
]
const stoneRadius = 1.7

// Brush pressure along the stroke (t from 0 to 1): a heavy landing, a steady body, a long taper as
// the brush lifts. Same profile as the original mark; `weight` scales it.
const weight = 0.85
function strokeWidth(t) {
  if (t < 0.12) {
    const u = t / 0.12
    return weight * (2.6 + 1.6 * u * u * (3 - 2 * u))
  }
  if (t < 0.62) return weight * (4.2 - 0.9 * ((t - 0.12) / 0.5))
  return weight * (0.35 + 2.95 * (1 - (t - 0.62) / 0.38) ** 1.35)
}

const radius = 9.4
const wobble = 0.3
const startDegrees = -52
const sweepDegrees = 318

/** Outline of the stroke: sample the circle, offset each point by half the width, close with round ends. */
function ensoPath() {
  const steps = 90
  const outer = []
  const inner = []
  for (let i = 0; i <= steps; i += 1) {
    const t = i / steps
    const angle = ((startDegrees - sweepDegrees * t) * Math.PI) / 180
    const r = radius + wobble * Math.sin(t * Math.PI * 2.3)
    const half = strokeWidth(t) / 2
    outer.push([centre + (r + half) * Math.cos(angle), centre + (r + half) * Math.sin(angle)])
    inner.push([centre + (r - half) * Math.cos(angle), centre + (r - half) * Math.sin(angle)])
  }
  const point = ([x, y]) => `${x.toFixed(2)} ${y.toFixed(2)}`
  const tip = strokeWidth(1) / 2
  const landing = strokeWidth(0) / 2
  return [
    `M${point(outer[0])}`,
    ...outer.slice(1).map(p => `L${point(p)}`),
    `A${tip.toFixed(2)} ${tip.toFixed(2)} 0 0 1 ${point(inner.at(-1))}`,
    ...inner.slice(0, -1).reverse().map(p => `L${point(p)}`),
    `A${landing.toFixed(2)} ${landing.toFixed(2)} 0 0 0 ${point(outer[0])}`,
    'Z',
  ].join(' ')
}

// The stroke's inner edge must stay clear of the stones at every point, or the mark reads as two
// objects pushed together.
const innerEdge = radius - wobble - (weight * 4.2) / 2
const stoneReach = Math.max(...stones.map(stone => Math.hypot(stone.x - centre, stone.y - centre))) + stoneRadius + 0.2
const clearance = innerEdge - stoneReach
if (clearance < 1.2) throw new Error(`Stones are ${clearance.toFixed(2)} units from the stroke; keep at least 1.2.`)

const path = ensoPath()
const stoneMarkup = stones
  .map(stone => `<ellipse cx="${stone.x}" cy="${stone.y}" rx="${stoneRadius + 0.2}" ry="${stoneRadius}" fill="${stone.colour}"/>`)
  .join('\n  ')

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${viewBox} ${viewBox}" width="128" height="128">
  <title>Zendo</title>
  <!-- Generated by scripts/suite-icon.mjs; edit the script, not this file. An ensō (the Zen brush
       circle) holding four stones, one per application: Ledger, Hanko, Sumi, Slides. -->
  <rect x="1" y="1" width="30" height="30" rx="8" fill="${plate}"/>
  <path fill="${ink}" d="${path}"/>
  ${stoneMarkup}
</svg>
`

const module = `// Generated by scripts/suite-icon.mjs; edit the script, not this file.
export const suitePlate = '${plate}'
export const suiteInk = '${ink}'
export const ensoPath = '${path}'
export const stoneRadius = ${stoneRadius}
export const stones = ${JSON.stringify(stones.map(({ colour, x, y }) => ({ colour, x, y })))} as const
`

writeFileSync('favicon.svg', svg)
writeFileSync('src/renderer/public/favicon.svg', svg)
writeFileSync('src/renderer/src/ui/suite-mark.ts', module)
console.log(`Suite mark written; stone clearance ${clearance.toFixed(2)} units.`)
